name: CI

on:
  # We run CI on pushes to the main branch
  push:
    branches:
      - main
  # and on all pull requests to the main branch
  pull_request:
    branches:
      - main
  # as well as upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:

jobs:
  test:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Checking out the cookie cutter repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install test requirements
      run: |
        python -m pip install -r requirements-dev.txt

    - name: Install Doxygen (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y doxygen

    - name: Install Doxygen (MacOS)
      if: runner.os == 'macOS'
      run: |
        brew install doxygen

    - name: Install Doxygen (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install -y doxygen.install

    - name: Set up git identity
      run: |
        git config --global user.email "ssc@citestuser.com"
        git config --global user.name "SSC CI Test User"

    - name: Run regular test suite
      run: |
        python -m pytest -k 'not deploy'

    - name: Set up SSH Agent to deploy to test repositories
      if: runner.os == 'Linux' && matrix.python-version == '3.8'
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: |
          ${{ secrets.GHA_TEST_PRIVATE_KEY }}

    - name: Add gitlab.com to the list of known hosts
      if: runner.os == 'Linux' && matrix.python-version == '3.8'
      run: |
        echo "gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9" >> ~/.ssh/known_hosts

    - name: Run deploy tests
      if: runner.os == 'Linux' && matrix.python-version == '3.8'
      env:
        GH_API_ACCESS_TOKEN: ${{ secrets.GH_API_ACCESS_TOKEN }}
        GL_API_ACCESS_TOKEN: ${{ secrets.GL_API_ACCESS_TOKEN }}
      run: |
        python -m pytest -k deploy
